# Generated by Django 3.0.1 on 2019-12-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('left_side_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('right_side_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('back_side_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MobileProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('brand', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=20)),
                ('battery', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('ram', models.FloatField(blank=True, max_length=5, null=True)),
                ('is_smart_phone', models.BooleanField(default=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ShirtProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('brand', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=120)),
            ],
            bases=('products.product',),
        ),
    ]
