# Generated by Django 3.0.1 on 2019-12-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtproduct',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='MobileProduct',
        ),
        migrations.DeleteModel(
            name='ShirtProduct',
        ),
    ]
