# Generated by Django 3.0.1 on 2019-12-23 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_sub', '0002_auto_20191223_1000'),
        ('products', '0002_auto_20191223_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_sub.SubCategory'),
        ),
    ]
