# Generated by Django 3.0.1 on 2019-12-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='category',
        ),
    ]
