# Generated by Django 3.0.1 on 2019-12-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191223_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_side_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='left_side_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='right_side_image',
        ),
    ]
