# Generated by Django 3.0.1 on 2019-12-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('none', 'None'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('furniture', 'Furniture'), ('books', 'Books')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=120)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_sub.Categories')),
            ],
        ),
    ]
