# Generated by Django 3.0.1 on 2019-12-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_sub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
