# Generated by Django 3.0.1 on 2019-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_sub', '0002_auto_20191223_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
